# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dec5de49c022fc960792886ed5247611cc9538cd6c8ff20249b96e3fd94fea0dabe07da1a3b7bcc0275ef8d28b79774d392913112d112bf35ef24c032757728

test:
  secret_key_base: 421601274d74cebe4806679ca4b36c9df0b7ee282367d04fa65f508b1786e3f1036bb40e586a6b0807b45a2255afbdcfbd0b03aeb0b20a8f2b841bb95685b8b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
